DUNNO = ["I blew a belt!","I can't process that sentence","Whoops! Something went wrong.", "Uh oh; one of us made an error!"]
REASK = "Could you rephrase or ask/assert something different?"
(N, SYMM, BASE, C, REGION, POLY) = (0,1,2,3,4,5)
GENERICS = ('polygon', 'shape', 'figure', 'object')
MINFRACTION = 7
TOP, RIGHT, BOTTOM, LEFT = 0,1,2,3
DEFNS = {3:"triangle",4:"quadrilateral",5:"pentagon",6:"hexagon",8:"octagon"}
REVDEFNS = {'triangle':3,'quadrilateral':4,'pentagon':5,'hexagon':6,'octagon':8}
SNUM = {'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8}
DNE = "That doesn't exist"
THEPROB = "Be more specific or more general"
YES = "Yes"
NO = "No"
